

/**
 * This interface allows an object to listen for
 * GameEvent's which are generated by a TetrisGame
 * everytime a game is started or stopped.
 * 
 * @author Scott Clee
 */
public interface GameListener
{
    /**
     * This method is invoked everytime a TetrisGame
     * is started or stopped.
     * 
     * @param event a GameEvent
     */
    public void gameChange(GameEvent event);
}
